name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: password

jobs:
  test:
    name: Node ${{ matrix.node }} with CouchDB ${{ matrix.couchdb }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
        os: [ubuntu-latest]
        couchdb: ["3.1", "3.0", "2.3"]

    steps:
      - name: Set up CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}

      - name: Test CouchDB
        run: |
          curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": $COUCHDB_USER, "password": $COUCHDB_USER}' http://127.0.0.1:5984/_session

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Global Dependencies
        run: npm install -g npm@latest

      - name: Get NPM Cache Directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Version
        run: |
          node --version
          npm --version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Coverage Test
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}-couchdb-${{ matrix.couchdb }}
          parallel: true

  finish:
    needs: test
    name: Finish
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
